services:
  - type: web
    name: seo-tool
    env: python
    plan: free  # optional: can be free, starter, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
